enum BoycottReason {
  CONSTRUCTION_OCCUPIED_LAND = 'CONSTRUCTION_OCCUPIED_LAND',
  SETTLEMENT_PRODUCTION = 'SETTLEMENT_PRODUCTION',
  EXPLOITATION_OCCUPIED_PRODUCTION_RESOURCES = 'EXPLOITATION_OCCUPIED_PRODUCTION_RESOURCES',
  SERVICES_SETTLEMENTS = 'SERVICES_SETTLEMENTS',
  PRIVATE_SECURITY_SURVEILLANCE_TECHNOLOGY = 'PRIVATE_SECURITY_SURVEILLANCE_TECHNOLOGY',
  SPECIALIZED_EQUIPMENT_SERVICES = 'SPECIALIZED_EQUIPMENT_SERVICES',
  WALL_CHECKPOINTS = 'WALL_CHECKPOINTS',
  PALESTINIAN_CAPTIVE_MARKET = 'PALESTINIAN_CAPTIVE_MARKET',
  ECONOMIC_EXPLOITATION = 'ECONOMIC_EXPLOITATION',
  POPULATION_CONTROL = 'POPULATION_CONTROL',
  SETTLEMENT_ENTERPRISE = 'SETTLEMENT_ENTERPRISE',
  MILITARY_EQUIPMENT = 'MILITARY_EQUIPMENT',
  EXPLOITATION_LABOUR = 'EXPLOITATION_LABOUR',
  ENVIRONMENTAL_DAMAGE = 'ENVIRONMENTAL_DAMAGE',
  DEMOLITION_EQUIPMENT = 'DEMOLITION_EQUIPMENT',
}

export default BoycottReason;
