import { z } from 'zod';

export const BoycottReasonSchema = z.enum([
  'CONSTRUCTION_OCCUPIED_LAND',
  'SETTLEMENT_PRODUCTION',
  'EXPLOITATION_OCCUPIED_PRODUCTION_RESOURCES',
  'SERVICES_SETTLEMENTS',
  'PRIVATE_SECURITY_SURVEILLANCE_TECHNOLOGY',
  'SPECIALIZED_EQUIPMENT_SERVICES',
  'WALL_CHECKPOINTS',
  'PALESTINIAN_CAPTIVE_MARKET',
  'ECONOMIC_EXPLOITATION',
  'POPULATION_CONTROL',
  'SETTLEMENT_ENTERPRISE',
  'MILITARY_EQUIPMENT',
  'EXPLOITATION_LABOUR',
  'ENVIRONMENTAL_DAMAGE',
  'DEMOLITION_EQUIPMENT',
]);

export type BoycottReasonType = `${z.infer<typeof BoycottReasonSchema>}`;

export default BoycottReasonSchema;
